version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    environment:
      JWT_SECRET: mySecretKeyForJWTTokenGenerationAndValidation
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - music-service
    networks:
      - backend

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/userdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8081:8081"
    networks:
      - backend

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/authdb
      SPRING_DATASOURCE_USERNAME: auth
      SPRING_DATASOURCE_PASSWORD: pass
      USER_SERVICE_URL: http://user-service:8081/api/users
      JWT_SECRET: mySecretKeyForJWTTokenGenerationAndValidation
    ports:
      - "8082:8082"
    depends_on:
      - user-service
    networks:
      - backend

  music-service:
    build:
      context: ./music-service
    container_name: music-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://music-db:5432/musicdb
      SPRING_DATASOURCE_USERNAME: music
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8083:8083"
    networks:
      - backend

networks:
  backend:
    driver: bridge
